### ISSUE TITLE
Some advice for the documentation

### ISSUE THREAD

**Issue by IoriOikawa** [b1f6c1c4/hub-sync#2]
0. If this is a software product, the documentation(user guide) must be highly accessible and comprehensible. Based on my own experience, the suggestions are below:

1. There should be a clear and simple way setting up the program. Users are holding eager demands to download tools, letting them satisfied from the first glance. Besides, users are tend to compare the existed methods based on the effort of time. What about providing a simplified usable example at the very first of the documentation?

2. When returning the error messages, clearly and briefly tell the user which part, or even which file is wrong. Throwing users around the different documentations is always a bad idea. Instead, providing quick instructions makes a tool handy.

3. When people doing one task, they tend to be sequential rather than combinational. That requires a sequential instructions categorizing each step for better understanding, with variations/options/selections comes last. It helps users getting their hands on the product fast and through. So how about changing the arrangement of the documentation into Setup-Usage-Motivation-Example-Variety(other functions)?

**Comment by b1f6c1c4** [comment]
@shisoft Any comments?

**Comment by shisoft** [comment]
A good document can have discussion in terms of different scenarios, with placeholder to tell the user what problem it can solve. Placeholders should be oblivious and there should be clear indication on what user need to do to suit their own needs. The example we had shows how to synchronize personal branches with `webpack`. For me I did not use node js at all, this example confused me until I was told it have to be forked first. A better way is to set `webpack` as the placeholder in your example, presume user have their own set of forks and they should pick one on their own. 
Upon receiving the error messages from GitHub, the application should translate server response to something more meaningful with how it can be fixed and what user did wrong, instead of put everything in the document and expect user will check on that in later time
If time is allowed, there can be some easy way to install this tool from scratch. A good example is rustup.rs, it allows you to install the rust tool chain in just one command. This requires efforts on development especially for cross-platform, but remove the hassle from users on installing it.
